In [1]:
import pandas as pd

In [2]:
import numpy as np

### After installing and importing numpy, let us get to work
**Note:** You can install and import in the same line.

In [3]:
fruits = ["Mango", "Orange", "Apple"]
np.array(fruits)

array(['Mango', 'Orange', 'Apple'], dtype='<U6')

In [4]:
fruits

['Mango', 'Orange', 'Apple']

In [5]:
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
my_list = [[1,2,3], [4,5,6],[7,8,9]]
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.arange(1,6,2)

array([1, 3, 5])

In [11]:
np.random.rand(10)

array([0.52347977, 0.44588787, 0.32644822, 0.99414313, 0.45789045,
       0.5240872 , 0.91287029, 0.81581483, 0.35856352, 0.21100279])

In [12]:
rand_num = np.random.rand(30)
rand_num

array([0.07054045, 0.73343059, 0.97279992, 0.55259257, 0.03654094,
       0.07947555, 0.16095522, 0.50918158, 0.1795085 , 0.31540128,
       0.1964639 , 0.10804715, 0.6863734 , 0.0908282 , 0.54266234,
       0.8102969 , 0.67255484, 0.13647599, 0.26108653, 0.15129448,
       0.86905839, 0.38025487, 0.17328526, 0.08879593, 0.25151132,
       0.04933984, 0.86133449, 0.59232456, 0.88244943, 0.9582204 ])

In [13]:
rand_num.shape

(30,)

In [14]:
rand_num_1 = rand_num.reshape(6,5)
rand_num_1

array([[0.07054045, 0.73343059, 0.97279992, 0.55259257, 0.03654094],
       [0.07947555, 0.16095522, 0.50918158, 0.1795085 , 0.31540128],
       [0.1964639 , 0.10804715, 0.6863734 , 0.0908282 , 0.54266234],
       [0.8102969 , 0.67255484, 0.13647599, 0.26108653, 0.15129448],
       [0.86905839, 0.38025487, 0.17328526, 0.08879593, 0.25151132],
       [0.04933984, 0.86133449, 0.59232456, 0.88244943, 0.9582204 ]])

In [15]:
rand_num_1.shape

(6, 5)

In [16]:
twenty = np.arange(20)
twenty

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
twenty[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [18]:
greater_than_7 = twenty > 7
greater_than_7

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [19]:
eight_up = twenty[greater_than_7]
eight_up

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
twenty[:8] * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [21]:
twenty[:8] = 60
twenty

array([60, 60, 60, 60, 60, 60, 60, 60,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
arr2d = [[1,2,3,4],
         [5,6,7,8],
         [9,10,11,12],
         [13,14,15,16]]
arr2d = np.array(arr2d)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
arr2d[:, 0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [33]:
pd.DataFrame(arr2d,my_index,my_index)

Justice  Musonda  Daniel  Orjji
Justice        1        2       3      4
Musonda        5        6       7      8
Daniel         9       10      11     12
Orjji         13       14      15     16

In [24]:
my_data = [1,2,3,4]
my_index = ["Justice", "Musonda", "Daniel", "Orjji"]

In [25]:
my_series = pd.Series(data=my_data, index=my_index)
my_series

Justice    1
Musonda    2
Daniel     3
Orjji      4
dtype: int64

In [26]:
my_series['Musonda']

2

In [27]:
df = pd.read_csv(r"C:\Users\USER\Downloads\tips.csv")
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [28]:
df.iloc[2]

total_bill                     21.01
tip                              3.5
sex                             Male
smoker                            No
day                              Sun
time                          Dinner
size                               3
price_per_person                 7.0
Payer Name            Travis Walters
CC Number           6011812112971322
Payment ID                   Sun4458
Name: 2, dtype: object

In [29]:
df[df["size"] > 2]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
1         10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No  Sun  Dinner     3              7.00   
4         24.59  3.61  Female     No  Sun  Dinner     4              6.15   
5         25.29  4.71    Male     No  Sun  Dinner     4              6.32   
7         26.88  3.12    Male     No  Sun  Dinner     4              6.72   
..          ...   ...     ...    ...  ...     ...   ...               ...   
227       20.45  3.00    Male     No  Sat  Dinner     4              5.11   
230       24.01  2.00    Male    Yes  Sat  Dinner     4              6.00   
231       15.69  3.00    Male    Yes  Sat  Dinner     3              5.23   
238       35.83  4.67  Female     No  Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No  Sat  Dinner     3              9.68   

          Payer Name         CC Number Payment ID  
1     Douglas Tucker  4478071379779230    Sun4608  
2     Travis Walters  6011812112971322    Sun4458  
4       Tonya Carter  4832732618637221    Sun2251  
5         Erik Smith   213140353657882    Sun9679  
7        Robert Buck  3514785077705092    Sun8157  
..               ...               ...        ...  
227   Robert Bradley   213141668145910    Sat4319  
230  Michael Osborne     4258682154026    Sat7872  
231      Jason Parks     4812333796161    Sat6334  
238   Kimberly Crane      676184013727    Sat9777  
239    Michael Avila  5296068606052842    Sat2657  

[84 rows x 11 columns]