In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

### After installing and importing numpy, let us get to work
**Note:** You can install and import in the same line.

In [4]:
fruits = ["Mango", "Orange", "Apple"]
np.array(fruits)

array(['Mango', 'Orange', 'Apple'], dtype='<U6')

In [5]:
fruits

['Mango', 'Orange', 'Apple']

In [8]:
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
my_list = [[1,2,3], [4,5,6],[7,8,9]]
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [18]:
np.arange(1,6,2)

array([1, 3, 5])

In [20]:
np.random.rand((5,5))

TypeError: 'tuple' object cannot be interpreted as an integer

In [38]:
rand_num = np.random.rand(30)
rand_num

array([0.20153542, 0.55632007, 0.356951  , 0.89244501, 0.32852504,
       0.47628789, 0.95754615, 0.42026889, 0.63965118, 0.89337347,
       0.73416826, 0.53216411, 0.68031162, 0.48188519, 0.5368353 ,
       0.66948988, 0.7200198 , 0.76954653, 0.03568723, 0.30200552,
       0.33830342, 0.89880188, 0.32559567, 0.02361551, 0.95553283,
       0.18957987, 0.20282819, 0.39704942, 0.45223117, 0.42532519])

In [39]:
rand_num.shape

(30,)

In [42]:
rand_num_1 = rand_num.reshape(6,5)
rand_num_1

array([[0.20153542, 0.55632007, 0.356951  , 0.89244501, 0.32852504],
       [0.47628789, 0.95754615, 0.42026889, 0.63965118, 0.89337347],
       [0.73416826, 0.53216411, 0.68031162, 0.48188519, 0.5368353 ],
       [0.66948988, 0.7200198 , 0.76954653, 0.03568723, 0.30200552],
       [0.33830342, 0.89880188, 0.32559567, 0.02361551, 0.95553283],
       [0.18957987, 0.20282819, 0.39704942, 0.45223117, 0.42532519]])

In [43]:
rand_num_1.shape

(6, 5)